name: Push
on:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  IMAGE: dvwassl
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build image
        run : docker build -t ${{ env.IMAGE }}:latest .

      - name: Tag image
        run : docker tag ${{ env.IMAGE }}:latest peco602/${{ env.IMAGE }}:latest

      - name: Push image
        run : docker push peco602/${{ env.IMAGE }}:latest